### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by swalayan-hasbuna** [ardananjungkusuma/catatan-keuangan#1]
cara instal gmn nih

**Comment by ardananjungkusuma** [comment]
1. Clone repo ini
2. Copy .env.example dan ubah menjadi .env
3. Download  [SQL FILE](https://github.com/ardananjungkusuma/catatan-keuangan/blob/main/db_catatankeuangan.sql) dan import ke phpmyadmin anda
4. Edit .env dan ubah konfigurasi database sesuai dengan server anda dan nama database yang anda import tadi
5. Lalu buka console dan jalankan `php artisan serve` dan buka browser `http://localhost:8000/`
